apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: incident-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: vishal28d/ingestion-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: platform-config
                  key: KAFKA_BOOTSTRAP_SERVERS
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: incident-platform
spec:
  selector:
    app: ingestion-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
