apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - kafka.yaml
  - mongodb.yaml
  - incident-service.yaml
  - ingestion-service.yaml
  - realtime-service.yaml
  - frontend.yaml
