global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@example.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'
  routes:
  - match:
      alertname: ServiceDown
    receiver: 'webhook'

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://ingestion-service:8081/api/v1/alerts/prometheus'
    send_resolved: true